name: actionlint

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/*.ya?ml'
      - 'Formula/a/actionlint.rb'
      - 'Formula/s/shellcheck.rb'
      - 'Formula/z/zizmor.rb'
  pull_request:
    paths:
      - '.github/workflows/*.ya?ml'

defaults:
  run:
    shell: bash -xeuo pipefail {0}

concurrency:
  group: "actionlint-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_ENV_HINTS: 1

permissions: {}

# FIXME: The `Install tools` step fails inside the Docker container for some reason.
jobs:
  workflow_syntax:
    if: github.repository_owner == 'Homebrew'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        id: setup-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          core: true
          cask: false
          test-bot: false

      - name: Install tools
        run: brew install actionlint shellcheck zizmor

      - name: Set up GITHUB_WORKSPACE
        env:
          HOMEBREW_TAP_REPOSITORY: ${{ steps.setup-homebrew.outputs.repository-path }}
        run: |
          # Annotations work only relative to GITHUB_WORKSPACE
          (shopt -s dotglob; rm -rf "${GITHUB_WORKSPACE:?}"/*; mv "${HOMEBREW_TAP_REPOSITORY:?}"/* "$GITHUB_WORKSPACE")
          rmdir "$HOMEBREW_TAP_REPOSITORY"
          ln -vs "$GITHUB_WORKSPACE" "$HOMEBREW_TAP_REPOSITORY"

      - run: zizmor --format sarif . > results.sarif

      - name: Upload SARIF file
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: results.sarif
          path: results.sarif

      - name: Set up actionlint
        run: |
          # Setting `shell: /bin/bash` prevents shellcheck from running on
          # those steps, so let's change them to `shell: bash` for linting.
          sed -i 's|shell: /bin/bash -x|shell: bash -x|' .github/workflows/*.y*ml
          # The JSON matcher needs to be accessible to the container host.
          cp "$(brew --repository)/.github/actionlint-matcher.json" "$HOME"
          echo "::add-matcher::$HOME/actionlint-matcher.json"

      - run: actionlint

  upload_sarif:
    needs: workflow_syntax
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Download SARIF file
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: results.sarif
          path: results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@60168efe1c415ce0f5521ea06d5c2062adbeed1b # v3.28.17
        with:
          sarif_file: results.sarif
          category: zizmor
